tellme2014/urls.py
from django.conf.urls.defaults import *
from django.conf.urls import patterns, include, url
from tellme2014.tellme  import views
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
#    # Examples:
#    # url(r'^$', 'tellme2014.views.home', name='home'),
#    # url(r'^tellme2014/', include('tellme2014.foo.urls')),
#
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns('tellme2014.tellme.views',
        (r'^$','index'),
        (r'^(?P<url>(cid)|(site)|(line)|(userinfo)|(jtid)|(service))/$','display'),

        (r'^(?P<url>(cid))/add/$','addcid'),
         (r'^(?P<url>(jtid))/add/$','addjtid'),
        (r'^(?P<url>(site))/add/(?P<id>\w+)/$','addsite'),
        (r'^(?P<url>(line))/add/(?P<id>\w+)/$','addline'),
        (r'^(?P<url>(service))/add/(?P<id>\w+)/$','addservice'),
        (r'^(?P<url>(jtid))/add/(?P<id>\w+)/$','addjtid'),
        #(r'^(?P<url>(userinfo))/add/(?P<id>\w+)/$','add'),

        (r'^(?P<url>(cid))/edit/(?P<id>\d+)/$','editcid'),
        (r'^(?P<url>(site))/edit/(?P<id>\w+)/$','editsite'),
        (r'^(?P<url>(line))/edit/(?P<id>\w+)/$','editline'),
        (r'^(?P<url>(service))/edit/(?P<id>\w+)/$','editline'),
       (r'^(?P<url>(jtid))/edit/(?P<id>\w+)/$','editjtid'),
        #(r'^(?P<url>(cid)|(site)|(line)|(userinfo))/edit/(?P<id>\w+)/$','edit'),

        (r'^(?P<url>(cid)|(site)|(line)|(userinfo)|(service))/del/(?P<id>\w+)/$','delete'),
	(r'^(?P<url>(cid)|(site)|(line)|(userinfo)|(service))/addmonitor/(?P<id>\w+)/$','addmonitor'),
	(r'^(?P<url>(cid)|(site)|(line)|(userinfo)|(service))/addmrtg/(?P<id>\w+)/$','mrtgadd'),
        (r'^(?P<url>(cid)|(site)|(line)|(userinfo)|(jtid)|(service))/list/(?P<id>\w+)/(?P<flag>\d{1})/$','list'),
      
        (r'^search/$','search'),
)


urlpatterns += patterns('tellme2014.tellme.login',
        (r'^login/$','login_view'),
        (r'^logout/$','logout_view'),
       # (r'^user/$','register'),
        #(r'^user/del/(?P<id>\d+)/$','delete'),
        (r'^user/change_pass/$','change_pass'),
        #(r'^user/setpassword/(?P<id>\d+)/$','setpassword'),
 )

#urlpatterns += patterns('',
#     (r'^static/bootstrap/(?P<path>.*)$', 'django.views.static.serve',
#      #{'document_root': '/var/www/django/tellme2014/tellme2014/'}),
#     {'document_root':   settings.STATIC_ROOT}),
#)

tellme2014/tellme/models.py
#coding: utf8
from django.db import models
from django.conf import settings
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib.auth.models import User
from django.template import RequestContext
from time import gmtime, strftime
from django.utils.timezone import now, timedelta
# Create your models here.
STATIC_CHOICES = (
    (u'ON', u'ON'),
    (u'OFF',u'OFF'),
     (u'ON_TEST',u'正在TEST'),
    (u'OFF_TEST',u'关闭TEST'),
)
servertype_CHOICES = (
    (u'Fastip', u'Fastip'),
    (u'组网',u'组网'),
    (u'Fastip+组网',u'Fastip+组网'),
    (u'设备销售',u'设备销售'),
    (u'Other',u'Other'),
)
class JituanID(models.Model):
      jtid = models.IntegerField(u'集团ID' ,max_length=255,primary_key=True)
      jtname = models.CharField(u'客户集团名称', max_length=255)
      status = models.CharField(u'状态', max_length=10,choices=STATIC_CHOICES,default=u'ON')
      jtcreate_date = models.DateField(u'创建日期')
      def __unicode__(self):
        return  u'%s -- %s ' % (self.jtid,self.jtname)
      
class Cid(models.Model):
    cid = models.IntegerField(u'CID' ,max_length=255,primary_key=True)
    contractname = models.CharField(u'客户合同名', max_length=50)
    typeid = models.CharField(u'安装名义', max_length=50 , default=u'东莞光联')
    jtid = models.ForeignKey(JituanID,on_delete=models.PROTECT)
    sales  = models.CharField(u'业务员', max_length=50)
    servertype = models.CharField(u'客户服务类型', max_length=10,choices=servertype_CHOICES,blank=True)
    bp  = models.CharField(u'BP', max_length=50, blank=True)
    mrtg_server = models.CharField(u'用户登录查看Mrtg流量服务器', max_length=255, blank=True)
    mrtg_pass = models.CharField(u'mrtg客户账号资料', max_length=255, blank=True)
    netflow_server = models.CharField(u'用户登录Netflow的服务器', max_length=255, blank=True)
    netflow_pass = models.CharField(u'netflow客户账号资料', max_length=255, blank=True)
    App_pass = models.CharField(u'App客户账号资料', max_length=255, blank=True)
    cid_rd = models.CharField(u'VRF_RD', max_length=50 , blank=True)
    status = models.CharField(u'客户状态', max_length=10,choices=STATIC_CHOICES,default=u'ON')
    cidcreate_date = models.DateField(u'创建日期')
    def __unicode__(self):
        return  u'%s --- %s ' % (self.cid,self.contractname)
    class Meta:
        ordering = ['-cid']
     #   get_latest_by = 'cid'

class Site(models.Model):
    cid = models.ForeignKey(Cid,on_delete=models.PROTECT)
    siteid = models.CharField(u'SiteID' ,max_length=255,primary_key=True)
    oldcid = models.CharField(u'旧的CID(old_cid)', max_length=255, blank=True)
    sitename = models.CharField(u'站点名', max_length=50)
    siteaddr  = models.CharField(u'地址', max_length=255)
    contacts  = models.CharField(u'联络人', max_length=50, blank=True)
    sitecontact  = models.CharField(u'联络资料', max_length=50, blank=True)
    siteemail  = models.CharField(u'联络Email', max_length=50, blank=True)
    status = models.CharField(u'站点状态', max_length=10,choices=STATIC_CHOICES,default=u'ON')
    sitecreate_date = models.DateField(u'创建日期')
    def __unicode__(self):
        return  u'%s -- %s ' % (self.cid,self.sitename)
    class Meta:
        ordering = ['-siteid']

class Line(models.Model):
    siteid = models.ForeignKey(Site,on_delete=models.PROTECT)
    lineid = models.CharField(u'LineID' ,max_length=255,primary_key=True)
    lineserviceid = models.CharField(u'LINE服务ID', max_length=50,blank=True)
    lineserver = models.CharField(u'接入服务器', max_length=50)
    pengpop=models.CharField(u'鹏博士POP', max_length=50,help_text="如果接入鹏博士POP，请选择POP区域")
    lineport = models.CharField(u'接入端口', max_length=50,blank=True)
    lineswitch = models.CharField(u'在那台Switch上', max_length=50,blank=True)
    lineswitchport = models.CharField(u'Switch端口', max_length=50,blank=True)
    lineaccesstype = models.CharField(u'接入类型', max_length=50) 
    linejifangtype = models.CharField(u'主/备类型', max_length=50,blank=True,help_text="例如:主光纤,备份线路")
    linewanip = models.CharField(u'WAN_IP', max_length=50, blank=True)
    linelanip = models.CharField(u'LAN_IP', max_length=50, blank=True)
    linejiankongip = models.CharField(u'监控IP地址:', max_length=50)
    linepass  = models.CharField(u'路由器用户和密码', max_length=50, blank=True)
    linebandwidth = models.CharField(u'线路频宽', max_length=50)
    linetype = models.CharField(u'线路厂商和类型', max_length=50, blank=True)
    linequan = models.CharField(u'线路所有权', max_length=50, blank=True)
    linelocalinfo = models.CharField(u'本地线路信息', max_length=50, blank=True)
    linenum =  models.CharField(u'线路编号', max_length=50, blank=True)
    linebaozhanginfo = models.CharField(u'线路报障资料', max_length=255, blank=True)
    lineservicenumber = models.CharField(u'公司服务编号', max_length=255, blank=True)
    linemrtgserver = models.CharField(u'流量服务器server', max_length=255, blank=True)
    linerrdid = models.CharField(u'流量图ID', max_length=50, blank=True)
    lineother = models.CharField(u'其他资料', max_length=65500, blank=True)
    status = models.CharField(u'Line状态', max_length=10,choices=STATIC_CHOICES,default=u'ON')
    linecreate_date = models.DateField(u'创建日期') 
    def __unicode__(self):
        return  u'%s --- %s ' % (self.siteid,self.lineid)
    class Meta:
        ordering = ['-lineid']

class Service(models.Model):
    serviceid = models.CharField(u'ServiceID' ,max_length=255,primary_key=True)
    siteid = models.ForeignKey(Site,on_delete=models.PROTECT)
    servicetype = models.CharField(u'服务类型', max_length=50)
    serviceserviceid = models.CharField(u'服务ID', max_length=255,blank=True)
    serviceshebei= models.CharField(u'包含的设备清单', max_length=255, blank=True)
    servicefeiyong= models.CharField(u'服务费用计算方式', max_length=255, blank=True)
    serviceother = models.CharField(u'其他资料', max_length=255, blank=True)
    status = models.CharField(u'Service状态', max_length=10,choices=STATIC_CHOICES,default=u'ON')
    servicecreate_date = models.DateField(u'创建日期') 
    def __unicode__(self):
        return  u'%s' % (self.servictype)
    class Meta:
        ordering = ['-serviceid']

tellme2014/templates/cid.html
{% extends "base.html" %}
{% block content %}
       <p>
       <div style="width:230px; float:left; overflow:hidden" >
        <form action="" method="POST"> {% csrf_token %} 
           请输入{{ type }}: <input type="text" name="q" />
                <input type="submit" value="查询">
            
        </form>
       </div>
        {% if  perms.tellme.add_cid %}
        <div style=float:right; >
         <td><a href="/{{ type }}/add/">增加cid</a></td>
        </div>
        {% endif %}
        {% if jieguo %}
                <p style="color: red;">你查询的结果如下！！</p>
        {% endif %}
        <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
        <th>客户CID</th><th>客户合同名</th><th>安装名义</th><th>业务员</th><th>BP</th><th>客户服务类型</th><th>客户状态</th><th>客户创建日期</th><th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for cid in room.object_list %}
        <tr>
        <td><a href="/cid/list/{{ cid.cid }}/1">{{ cid.cid }}</a></td>
        <td>{{ cid.contractname }}</td>
        <td>{{ cid.typeid }}</td> 
        <td>{{ cid.sales}}</td>
        <td>{{ cid.bp}}</td>
        <td>{{ cid.servertype}}</td>
        <td><span style="color:red"> {{ cid.status }}</span> </td>
        <td>{{ cid.cidcreate_date }}</td> 
        <td>
           {% if  perms.tellme.change_cid %}
           <a href="/cid/edit/{{ cid.cid }}">修改</a>&nbsp; &nbsp;
           {% endif %}
           {% if  perms.tellme.add_site %}
           <a href="/site/add/{{ cid.cid }}">增加Site</a>&nbsp; &nbsp;
           {% endif %}
           {% if  perms.tellme.delete_cid %}
           <a href="del/{{ cid.cid }}">删除</a>
           {% endif %}
           </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        </p>
{% endblock %}

tellme2014/templates/cidaddok.html
{% extends "base.html" %}
{% block content %}
 <p style="color: red;">
          增加CID:{{ cid }}&nbsp;OK
        </p>
<div class="form-actions">
        <a href="/cid/add"><button  style="btn btn-primary">增加新的CID</button></a>
           &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
         <a href="/site/add/{{ cid }}" ><button  style="btn btn-primary">增加CID:{{ cid }}站点资料</button></a>
　　　　　&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
    </div> 
{% endblock %}

tellme2014/templates/linelist.html
{% extends "base.html" %}
{% block content %}
       <p>
            <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
       <th>客户CID</th><th>客户合同名</th><th>安装名义</th><th>业务员</th><th>BP</th><th>MRTG/Netflow资料</th><th>客户状态</th><th>客户创建日期</th><th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for cid in cidroom.object_list %}
        <tr>
        <td><a href="/cid/list/{{ cid.cid }}/{{ flag }}">{{ cid.cid }}</a></td>
        <td>{{ cid.contractname }}</td>
        <td>{{ cid.typeid }}</td>
        <td>{{ cid.sales}}</td>
        <td>{{ cid.bp}}</td>
        <td>{{ cid.mrtg_netflow}}</td>
        <td><span style="color:red"> {{ cid.status }}</span> </td>
        <td>{{ cid.cidcreate_date }}</td>
        <td>
         {% if  perms.tellme.change_cid %}
         <a href="/cid/edit/{{ cid.cid }}">修改</a>&nbsp; &nbsp;
          
               
         {% endif %}
         {% if  perms.tellme.add_site %}
         <a href="/site/add/{{ cid.cid }}">增加Site</a>&nbsp; &nbsp;
         {% endif %}
         {% if  perms.tellme.delete_cid %}
          <a href="del/{{ cid.cid }}">删除</a>
         {% endif %}
         </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
         <th>站点ID</th><th>站点名</th><th>站点地址</th><th>联络人</th><th>联络电话</th><th>联络Email</th><th>站点状态</th><th>创建日期</th><th>站点图片</th><th>操作</th>
        </tr>
        </thead>
        <tbody>
        
        <tr>
        <td><a href="/site/list/{{ site.siteid }}/{{ flag }}">{{ site.siteid }}</a></td>
        <!-- <td>{{ site.oldcid }}</td> -->
        <td>{{ site.sitename }}</td>
        <td>{{ site.siteaddr }}</td>
        <td>{{ site.contacts }}</td>
        <td>{{ site.sitecontact}}</td>
        <td>{{ site.siteemail }}</td>
        <td><span style="color:red"> {{ site.status }}</span> </td>
        <td>{{ site.sitecreate_date }}</td> 
        <td><a href="/image/cid_image/{{ site.siteid }}/" rel="external">查看站点图片</a></td>
        <td>
          {% if  perms.tellme.change_site %}
          <a href="/site/edit/{{ site.siteid }}">修改</a>&nbsp; &nbsp;
          <a href="/image/upload.php?cid={{ site.siteid }}" rel="external">增加站点图片</a>&nbsp; &nbsp;
          {% endif %}
           {% if  perms.tellme.add_service %}
             <a href="/service/add/{{ site.siteid }}">增加站点服务(service)</a>&nbsp; &nbsp;
           {% endif %}
          {% if  perms.tellme.add_line %}
          <a href="/line/add/{{ site.siteid }}">增加Line</a>&nbsp; &nbsp;
          {% endif %}
          {% if  perms.tellme.delete_site %}
          <a href="/site/del/{{ site.siteid }}">删除</a>&nbsp; &nbsp;
          {% endif %}
          <a href="/site/list/{{ site.siteid }}/0">显示OFF状态</a>
         </td>
        </tr>
        
        </tbody>
        </table>

        <table class="table table-striped table-bordered table-condensed">
        <thead>
        </thead>
        <tbody>
        {% for line in room.object_list %}
            
        <tr>
        <th>线路ID:&nbsp; &nbsp;</th><td>{{ line.lineid }}</a></td>
        </tr>
        <tr>
        <th>接入服务器:&nbsp; &nbsp;</th><td>{{ line.lineserver }}</a></td>
        </tr>
	<tr>
        <th>鹏博士POP:&nbsp; &nbsp;</th><td>{{ line.pengpop }}</a></td>
        </tr>
        <tr>
        <th>接入端口:&nbsp; &nbsp;</th><td>{{ line.lineport }}</td>
        </tr>
        <tr>
        <th>Switch号:&nbsp; &nbsp;</th><td>{{ line.lineswitch}}</td>
         </tr>
        <tr>
        <th>Switch接口端口:&nbsp; &nbsp;</th><td>{{ line.lineswitchport}}</td>
         </tr>
        <tr> 
       <th>接入类型:&nbsp; &nbsp;</th><td>{{ line.lineaccesstype}}</td>
        </tr>
        <tr>
        <th>机房端口类型(主/备):&nbsp; &nbsp;</th><td>{{ line.linejifangtype}}</td>
        </tr>
        <tr>
        <th>WAN_IP:&nbsp; &nbsp;</th><td>{{ line.linewanip}}</td>
          </tr>
        <tr>
        <th>LAN_IP:&nbsp; &nbsp;</th><td>{{ line.linelanip }}</td>
          </tr>
        <th>监控ip地址:&nbsp; &nbsp;</th><td>{{ line.linejiankongip }}</td>
          </tr>
        <tr>
        <th>路由器用户和密码:&nbsp; &nbsp;</th><td>{{ line.linepass }}</td>
          </tr>
         <tr>
        <th>线路频宽:&nbsp; &nbsp;</th><td>{{ line.linebandwidth }}</td>
          </tr>
          <tr>
        <th>线路所有权:&nbsp; &nbsp;</th><td>{{ line.linequan }}</td>
          </tr>
        <tr>
        <th>线路厂商和类型:&nbsp; &nbsp;</th><td>{{ line.linetype }}</td>
          </tr>
        <tr>
        <th>本地线路信息:&nbsp; &nbsp;</th><td>{{ line.linelocalinfo }}</td>
          </tr>
         <tr>
        <th>线路编号:&nbsp; &nbsp;</th><td>{{ line.linenum }}</td>
          </tr>
        <th>线路报障资料:&nbsp; &nbsp;</th><td>{{ line.linebaozhanginfo }} </td>
           </tr>
          <tr>
        <th>公司服务编号:&nbsp; &nbsp;</th><td>{{ line.lineservicenumber }}</td>
           </tr>
         <tr>
        <th>其他资料:&nbsp; &nbsp;</th><td>{{ line.lineother }}</td>
          </tr>
        <tr>
         <tr> 
       <th>Line状态:&nbsp; &nbsp;</th><td><span style="color:red"> {{ line.status }}</span> </td>
        </tr>
         <tr>
        <th>创建时间:&nbsp; &nbsp;</th><td>{{ line.linecreate_date }}</td>
          </tr>
        <tr>
        <th>config:&nbsp; &nbsp;</th><td><a href="http://center.fnetlink.com.hk:10080/cgi-bin/rodge.pl?name={{ line.lineid }}" rel='external' >查看
     {{ line.lineid }}最新config</td>
          </tr>
        <th>操作:&nbsp; &nbsp;</th>
        <td>
         {% if  perms.tellme.change_line %}
           <a href="/line/edit/{{ line.lineid }}">修改</a>&nbsp; &nbsp;
         {% endif %}
         {% if  perms.tellme.delete_line %}
           <a href="/line/del/{{ line.lineid }}">删除</a>
         {% endif %}
         </td>
        </tr>
        <tr>
        </tr>
        </tbody> 
        </table>
      {%if line.linerrdid %}
        <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
        <th>每天流量</th>
        <tr>
        </thead>
        <tbody>
        <tr>
        <td><img src="http://{{ line.linemrtgserver }}/graph_image1.php?action=view&rra_id=1&local_graph_id={{ line.linerrdid }}"></td>
        </tr>
        </tbody>
        </table>

        <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
        <th>每周流量</th>
        <tr>
        </thead>
        <tbody>
        <tr>
       <td><img src="http://{{ line.linemrtgserver }}/graph_image1.php?action=view&rra_id=2&local_graph_id={{ line.linerrdid }}"></td>
        </tr>
        </tbody>
        </table>

        <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
        <th>每月流量</th>
        <tr>
        </thead>
        <tbody>
        <tr>
       <td><img src="http://{{ line.linemrtgserver }}/graph_image1.php?action=view&rra_id=3&local_graph_id={{ line.linerrdid }}"></td>
        </tr>
        </tbody>
        </table>

       <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
        <th>每年流量</th>
        <tr>
        </thead>
        <tbody>
        <tr>
       <td><img src="http://{{ line.linemrtgserver }}/graph_image1.php?action=view&rra_id=4&local_graph_id={{ line.linerrdid }}"></td>
        </tr>
        </tbody>
        </table>
        {% endif %}
        {% endfor %}
        
        </p>
{% endblock %}

tellme2014/templates/messages.html
<!DOCTYPE html>
<html>
<body>
<script>
        var lineid="{{id}}"
        alert(lineid+"监控已经添加");
        location.replace(document.referrer);
</script>
</body>
</html>

tellme2014/templates/mrtg.html
{% extends "base.html" %}
{% block search  %} 
<div style="width:230px; float:left; overflow:hidden" >
        <form action="" method="POST">
     <select name="select" size="4"  >
         <option value="cid" selected>CID</option>
         <option value="name">客户名</option>
         <option value="addr" >地址</option>
         <option value="ip">IP</option>
     </select>  
       <input type="text" name="q" />
             <input type="submit" value="查询">
        </form>
</div>
{% endblock %}

tellme2014/templates/servicelist.html
{% extends "base.html" %}
{% block content %}
       <p>
            <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
       <th>客户CID</th><th>客户合同名</th><th>安装名义</th><th>业务员</th><th>BP</th><th>MRTG/Netflow资料</th><th>客户状态</th><th>客户创建日期</th><th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for cid in cidroom.object_list %}
        <tr>
        <td><a href="/cid/list/{{ cid.cid }}/{{ flag }}">{{ cid.cid }}</a></td>
        <td>{{ cid.contractname }}</td>
        <td>{{ cid.typeid }}</td>
        <td>{{ cid.sales}}</td>
        <td>{{ cid.bp}}</td>
        <td>{{ cid.mrtg_netflow}}</td>
        <td><span style="color:red"> {{ cid.status }}</span> </td>
        <td>{{ cid.cidcreate_date }}</td>
        <td>
         {% if  perms.tellme.change_cid %}
         <a href="/cid/edit/{{ cid.cid }}">修改</a>&nbsp; &nbsp;
          
               
         {% endif %}
         {% if  perms.tellme.add_site %}
         <a href="/site/add/{{ cid.cid }}">增加Site</a>&nbsp; &nbsp;
         {% endif %}
         {% if  perms.tellme.delete_cid %}
          <a href="del/{{ cid.cid }}">删除</a>
         {% endif %}
         </td>
        </tr>
        {% endfor %}
        </tbody>
        </table>
        <table class="table table-striped table-bordered table-condensed">
        <thead>
        <tr>
         <th>站点ID</th><th>站点名</th><th>站点地址</th><th>联络资料</th><th>站点状态</th><th>创建日期</th><th>站点图片</th><th>操作</th>
        </tr>
        </thead>
        <tbody>
        
        <tr>
        <td><a href="/site/list/{{ site.siteid }}/{{ flag }}">{{ site.siteid }}</a></td>
        <td>{{ site.sitename }}</a></td>
        <td>{{ site.siteaddr }}</td>
        <td>{{ site.sitecontact}}</td>
        <td><span style="color:red"> {{ site.status }}</span> </td>
        <td>{{ site.sitecreate_date }}</td> 
        <td><a href="/image/cid_image/{{ site.siteid }}" rel="external">查看站点图片</a></td>
        <td>
          {% if  perms.tellme.change_site %}
          <a href="/site/edit/{{ site.siteid }}">修改</a>&nbsp; &nbsp;
          <a href="/image/upload.php?cid={{ site.siteid }}" rel="external">增加站点图片</a>&nbsp; &nbsp;
          {% endif %}
           {% if  perms.tellme.add_service %}
             <a href="/service/add/{{ site.siteid }}">增加站点服务(service)</a>&nbsp; &nbsp;
           {% endif %}
          {% if  perms.tellme.add_line %}
          <a href="/line/add/{{ site.siteid }}">增加line</a>&nbsp; &nbsp;
          {% endif %}
          {% if  perms.tellme.delete_site %}
          <a href="/site/del/{{ site.siteid }}">删除</a>&nbsp; &nbsp;
          {% endif %}
          <a href="/site/list/{{ site.siteid }}/0">显示OFF状态</a>
         </td>
        </tr>
        
        </tbody>
        </table>

        <table class="table table-striped table-bordered table-condensed">
        <thead>
        </thead>
        <tbody>
        {% for service in room.object_list %}
            
        <tr>
        <th>服务ID:&nbsp; &nbsp;</th><td>{{ service.serviceid }}</a></td>
        </tr>
        <tr>
        <th>服务类型:&nbsp; &nbsp;</th><td>{{ service.servicetype }}</a></td>
        </tr>
        <tr>
        <th>包含的设备清单:&nbsp; &nbsp;</th><td>{{ service.serviceshebei }}</td>
        </tr>
        <tr>
        <th>服务费用计算方式:&nbsp; &nbsp;</th><td>{{ service.servicefeiyong}}</td>
         </tr>
        <tr>
        <th>其他资料:&nbsp; &nbsp;</th><td>{{ service.serviceother}}</td>
         </tr>
        
        
         <tr> 
       <th>service状态:&nbsp; &nbsp;</th><td><span style="color:red"> {{ service.status }}</span> </td>
        </tr>
         <tr>
        <th>创建时间:&nbsp; &nbsp;</th><td>{{ service.servicecreate_date }}</td>
          </tr>
        <th>操作:&nbsp; &nbsp;</th>
        <td>
         {% if  perms.tellme.change_service %}
           <a href="/service/edit/{{ service.serviceid }}">修改</a>&nbsp; &nbsp;
         {% endif %}
         {% if  perms.tellme.delete_service %}
           <a href="/service/del/{{ service.serviceid }}">删除</a>
         {% endif %}
         </td>
        </tr>
        <tr>
        </tr>
        </tbody> 
        </table>
        {% endfor %}
        
        </p>
{% endblock %}